### ISSUE TITLE
Request: Path parameter on invalidate-cache.

### ISSUE THREAD

**Issue by viniciusclerod** [dafiti-group/orb-standard-pipeline#20]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the problem imposed by not having this feature

When we need to apply a cache **invalidation** to a distribution in **CloudFront**, we cannot apply it to a specific path (eg. `/folder/file.js`), only to all paths (`/*`).

### Describe the solution you'd like

A possible solution would be to add an optional path parameter in the job `invalidate-cache`, which had a default value corresponding to `/*`, as demonstrated below:

```yaml
version: '2.1'
orbs:
  dft: dafiti-group/orb-standard-pipeline@2.0.0
workflows:
  deployment-flow:
    jobs:
      - dft/invalidate-cache:
          cloudfront_id: XPTO12324
          path: /folder/file.ext
          context:
            - DEFAULT
            - QA         
```
